//AJAX
export const BEGIN_AJAX_CALL = "BEGIN_AJAX_CALL";
export const AJAX_ERROR = "AJAX_ERROR";

//CANDIDATES
export const CREATE_CANDIDATE = "CREATE_CANDIDATE";
export const GET_CANDIDATES_SUCCESS = "GET_CANDIDATES_SUCCESS";
export const GET_CANDIDATE_SUCCESS = "GET_CANDIDATE_SUCCESS";
